To make it compatible with Linux 6.11.x
pop-os/system76-dkms pull request #68
Opened 2024-08-15 14:22 UTC by beholders-eye

With Linux-6.11, we need this change for it to build successfully.

2024-08-15 14:22 UTC, beholders-eye commented
Tried it locally after opening #67

2024-08-15 14:54 UTC, crawfxrd commented
Ref:

- torvalds/linux@5c5a7680e67 ("platform: Provide a remove callback that returns no value")
- torvalds/linux@0edb555a65d1 ("platform: Make platform_driver::remove() return void")

2024-08-15 14:56 UTC, crawfxrd requested changes
This needs handling for using with older kernels.

Ref: https://github.com/pop-os/system76-acpi-dkms/blob/7bae1af5698a149481501c9dfdc7f05cd53792cb/system76_acpi.c#L808

2024-08-15 21:23 UTC, beholders-eye commented
> This needs to handle <6.11.0 and >=6.11.0 kernels.
> 
> Ref: https://github.com/pop-os/system76-acpi-dkms/blob/7bae1af5698a149481501c9dfdc7f05cd53792cb/system76_acpi.c#L808

Thanks for pointing that out. Done.

2024-08-15 21:29 UTC, crawfxrd commented on system76.c
> +	return 0
semicolon was removed

2024-08-19 11:08 UTC, beholders-eye commented on system76.c
> +	return 0
Thanks @crawfxrd, missed that.

2024-08-19 14:05 UTC, crawfxrd approved these changes

2024-10-08 16:14 UTC, jacobgkau approved these changes
Looks good. Not affecting the code path or behavior on 6.9. Still building as expected for Pop!_OS. Also builds & able to load/unload for kernel 6.11 (tested with Arch).

2024-10-08 22:27 UTC, merged